---
- hosts:              all
  gather_facts:       no
  become:             yes

  tasks:
    - name:           Remove unneeded packages
      shell:          sudo apt-get autoremove -y

    - name:           Clean up the repository
      shell:          sudo apt-get clean -y

    - name:           Update the apt cache
      apt:
        update_cache: yes

    - name:           Remove log files
      shell:          rm -rf /var/logs/*

    - name:           Remove cache files
      shell:          rm -rf /var/cache/*
