all:
  hosts:
    192.168.5.2:
#    192.168.10.[2-7]:
    192.168.20.[2-7]:
  children:
    masters:
      hosts:
#        192.168.10.2:
        192.168.20.2:
    workers:
      hosts:
#        192.168.10.[3-7]:
        192.168.20.[3-7]:
    dev:
      hosts:
        192.168.5.2:
    pvt:
      hosts:
        192.168.10.[2-7]:
    prod:
      hosts:
        192.168.20.[2-7]:
    jetson:
      hosts:
#        192.168.10.7:
         192.168.20.7:
