---
- all:
    hosts:
      ansible_host:    192.168.5.2
#      192.168.10.[2-7]:
      ansible_host:    192.168.20.[2-7]
  children:
    masters:
      hosts:
#        192.168.10.2:
        ansible_host:  192.168.20.2
    workers:
      hosts:
#        192.168.10.[3-7]:
        ansible_host:  192.168.20.[3-7]
    dev:
      hosts:
        ansible_host:  192.168.5.2
    pvt:
      hosts:
        ansible_host:  192.168.10.[2-7]
    prod:
      hosts:
        ansible_host:  192.168.20.[2-7]
    jetson:
      hosts:
#        192.168.10.7:
         ansible_host: 192.168.20.7
