all:
  hosts:
    192.168.5.2:
#    192.168.10.[2-7]:
    192.168.5.10[0-4]:
  children:
    masters:
      hosts:
#        192.168.10.2:
        192.168.5.100:
    workers:
      hosts:
#        192.168.10.[3-7]:
        192.168.5.10[1-4]:
    dev:
      hosts:
        192.168.5.2:
    pvt:
      hosts:
        192.168.10.[2-7]:
    prod:
      hosts:
        192.168.5.10[0-4]:
      vars:
        ansible_user=vagrant
        ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
    jetson:
      hosts:
#        192.168.10.7:
         192.168.20.7:
