{
 "title": "Jenkins Overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Jenkins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "vm_uptime_milliseconds" }
   ]
  },
  {
   "title": "Plugins active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "Plugins withUpdate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jenkins_plugins_withUpdate" }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_offline_value" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Plugins inactive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "Plugins failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_node_builds_count" }
   ]
  },
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration)/sum(jenkins_job_building_duration_count))"
    }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_unstable_total" }
   ]
  }
 ]
}